### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by acapet** [MAST-ULiege/GHER-POSTPROC#1]
- [ ] : adapt PROCESS function for 2D variables
- [ ] : variable EPOT, EPOT_T, EPOT_S
- [ ] : variable MLD
- [x] : variable CCC
- [x] : Enable optional mask arguments, with several dimension possibilities
- [x] : test gstore on 3D variables (DEN)
- [ ] : Hoevemuller
- [x] : Dedicated plotting functions
- [ ] : etc ...

**Comment by acapet** [comment]
- [x] : Output auxilliary netcdf files with only requested variables, copying dimensions and attributes from the original netcdf file.

**Comment by acapet** [comment]
* [ ] Ensures dx and dy are properly initiated (ie. not a single value but dx should vary with lat).

**Comment by acapet** [comment]
Some dedicated plot pfunction now availables .. for profiles, climatologies, 2D time-stacks and 1D time series.
